- name: Configure Nginx
  tags: configure
  block:
  - name: Copy config files
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: "nginx.conf.j2", dest: "/etc/nginx/nginx.conf" }
      - { src: "domain.j2", dest: "/etc/nginx/sites-available/{{ domain }}" }
      
  - name: Create link to domain file
    file:
      src: "/etc/nginx/sites-available/{{ domain }}"
      dest: "/etc/nginx/sites-enabled/{{ domain }}"
      state: link
      mode: '0755'

  - name: Create suite directory
    file:
      path: "{{ root_dir }}"
      state: directory
      recurse: yes
      mode: '0755'

  - name: Copy index.html in suite directory
    template:
      src: index.html.j2
      dest: "{{ root_dir }}/index.html"

  - name: Change config file
    replace:
      path: "/etc/nginx/nginx.conf"
      regexp: '# server_names_hash_bucket_size 64;'
      replace: 'server_names_hash_bucket_size 64;'

  - name: Reload nginx service
    systemd:
      name: nginx
      state: reloaded

  - name: Check site status
    ansible.builtin.uri:
      url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      return_content: yes
    register: result

  - debug:
      msg: "Server status: {{ result.status }}"