- name: Install Nginx package
  tags: install
  block:
  - name: Update repositories cache and install nginx package
    apt:
      name: nginx={{ nginx_ver }}
      update_cache: yes

  - name: Allow HTTP port in firewalld
    ufw:
      rule: allow
      name: Nginx HTTP

  - name: Start and Enabe nginx
    systemd:
      name: nginx
      enabled: yes
      state: started